### ISSUE TITLE
"UID variable is not set" issue

### ISSUE THREAD

**Issue by olberger** [jpetazzo/obs-docker#2]
I've tried to run docker-compose on my Debian testing system and got :
```
$ docker-compose up
WARNING: The UID variable is not set. Defaulting to a blank string.
ERROR: Missing mandatory value for "command" option in service "obs": please 'export UID'
```
Any clues ?

**Comment by olberger** [comment]
issueing "export UID" before running docker-compose did the trick, as expected ;-)

Maybe worth a mention in README, for bummers like me ? ;-)

**Comment by jpetazzo** [comment]
You're 100% right :)

I do it _slightly_ differently:

```bash
echo UID=$UID >> .env
```

... and that way you don't have to `export UID` each time.

I'll update the README, thanks!
