### ISSUE TITLE
Issue pulling nixery.dev/shell/ffmpeg/gphoto2

### ISSUE THREAD

**Issue by olberger** [jpetazzo/obs-docker#3]
Uh...

Pulling eos1100d (nixery.dev/shell/ffmpeg/gphoto2:)...
ERROR: error parsing HTTP 404 response body: unexpected end of JSON input: ""

Probably some disappeared repo :-/

**Comment by jpetazzo** [comment]
It's up again :-)

Funny story, after getting your message, I tried to host my own Nixery instance. I realized that the local storage option didn't work well (nixery.dev is using GCS to store blobs), so I sent a PR, and in the meantime, nixery.dev came back up.

I'm still planning to have my own Nixery instance, but it's now a lower priority project!
