### ISSUE TITLE
Debian seems to support virtual webcam output "out of the box"

### ISSUE THREAD

**Issue by olberger** [jpetazzo/obs-docker#4]
In Debian testing, it seems to me that the virtual webcam output is supported out of the box without additional plugins compilation.

As you've based the OBS runtime on Ubuntu, maybe that wouldn't help, but correct me if I'm wrong, wouldn't it allow to get rid from one of the components ?

**Comment by jpetazzo** [comment]
Yes, that's correct!

The only downside is that it doesn't let you pick the output (it picks the first available one), but other than that, it seems to work well; so I'll remove the v4l2 sink.

Thanks!

**Comment by jpetazzo** [comment]
... OK, I upgraded the Ubuntu Dockerfile to 20.04 and it still doesn't have virtual webcam output. So I'll let the v4l2sink in the Ubuntu Dockerfile for the time being :)
